[profile.default]
solc_version = "0.8.22"
optimizer = true
optimizer_runs = 200
src = "src"
out = "out"
libs = ["lib"]
via_ir=true

remappings = [
    "foundry-rs/forge-std=lib/forge-std/src/",
    "@balancer/contracts/=src/arbitrage/interfaces/",
    "@openzeppelin/openzeppelin-contracts/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
    "@uniswap/v3-core/contracts/=lib/v3-core/contracts/",
    "@aave/v3-core/contracts=lib/aave-v3-core/contracts",
    "@compound/contracts=lib/comet/contracts",
    "@interop-lib/=lib/interop-lib/src/",
    "@ethereum-optimism/optimism/packages/contracts-bedrock=lib/optimism/packages/contracts-bedrock",
    "@solady/=lib/solady/src/"
]

fuzz_runs = 1000

[profile.ci]
verbosity = 4

gas_reports = ["optimal"]


[etherscan]
84532 = { key = "${API_KEY}", url = "https://api-sepolia.basescan.org/api" }

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL_2}"
op-sepolia = "${OP_SEPOLIA_RPC_URL}"
